version: "3"

services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    command: sh docker-entrypoint.sh
    volumes:
      - .:/var/www
    ports:
      - "3333:3000"
    depends_on:
      - redis
    #   - db
    # environment:
    #   RAILS_ENV: development
    #   DATABASE_PASSWORD: root
    #   DATABASE_HOST: db
    #   DATABASE_PORT: 3306
  redis:
    image: redis
  # db:
  #   image: mysql:8.0
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
  #   platform: linux/x86_64
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root